### ISSUE TITLE
Change theme mode

### ISSUE THREAD

**Issue by P5ina** [shoh-dev/fcnui#1]
How do I change theme mode? Do I need to use MaterialApp themeMode?

**Comment by komiljonovshohjahon** [comment]
Theme scheme or theme can be changed using:
`fcnGetIt.get<Store<AppState>>().dispatch(ChangeFlexSchemeAction(flexScheme: FlexScheme.red.name));`
`fcnGetIt.get<Store<AppState>>().dispatch(ChangeThemeMode(ChangeThemeModeAction(themeMode: ThemeMode.dark));`
