### ISSUE TITLE
fcnui add Card

### ISSUE THREAD

**Issue by DesmondLouis** [shoh-dev/fcnui#2]
Server error: The connection errored: Connection refused This indicates an error which most likely cannot be solved by the library.

**Comment by komiljonovshohjahon** [comment]
Hi, are you trying to run locally?

**Comment by shohibexlab** [comment]
And by the way, card component is not included yet.
I am still working on core functionality and documentation, so I made only a button for now.
Once I finish documentation website, I will start making other components.

**Comment by komiljonovshohjahon** [comment]
And by the way, the card component is not included yet.
I am still working on core functionality and documentation, so I made only a button for now.
Once I finish the documentation website, I will start making other components.

**Comment by komiljonovshohjahon** [comment]
Card is also added.
https://fcnui.shoh.dev/docs/components/card
